# Generated by Django 4.0.4 on 2022-07-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskmanager_app', '0006_task_phase_task_row_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='owner',
            new_name='creator',
        ),
    ]
